import { AuctionQuestion } from "@/types/arena";

export const SAMPLE_AUCTION_QUESTIONS: AuctionQuestion[] = [
  // ==========================================
  // CATEGORY: AI & MACHINE LEARNING (1-10)
  // ==========================================
  {
    id: "q-001",
    question_number: 1,
    category: "AI & Machine Learning",
    difficulty: "Easy",
    base_price: 100,
    reward_points: 250,
    question_text: "What does the 'GPT' in ChatGPT officially stand for?",
    answer_clue: "Generative Pre-trained Transformer",
    status: "AVAILABLE",
  },
  {
    id: "q-002",
    question_number: 2,
    category: "AI & Machine Learning",
    difficulty: "Medium",
    base_price: 200,
    reward_points: 450,
    question_text: "Which milestone 2017 research paper introduced the Transformer architecture with self-attention mechanism?",
    answer_clue: "'Attention Is All You Need' (Vaswani et al., Google Brain / Research)",
    status: "AVAILABLE",
  },
  {
    id: "q-003",
    question_number: 3,
    category: "AI & Machine Learning",
    difficulty: "Hard",
    base_price: 300,
    reward_points: 700,
    question_text: "What mathematical technique freezes pre-trained model weights and injects trainable rank decomposition matrices to fine-tune LLMs with massive memory reduction?",
    answer_clue: "LoRA (Low-Rank Adaptation)",
    status: "AVAILABLE",
  },
  {
    id: "q-004",
    question_number: 4,
    category: "AI & Machine Learning",
    difficulty: "Easy",
    base_price: 120,
    reward_points: 280,
    question_text: "Which activation function is defined as f(x) = max(0, x) and helps mitigate the vanishing gradient problem in deep networks?",
    answer_clue: "ReLU (Rectified Linear Unit)",
    status: "AVAILABLE",
  },
  {
    id: "q-005",
    question_number: 5,
    category: "AI & Machine Learning",
    difficulty: "Medium",
    base_price: 220,
    reward_points: 500,
    question_text: "In diffusion models, what is the reverse process called where noise is iteratively removed to generate a clear image?",
    answer_clue: "Denoising (or Reverse Diffusion / Sampling)",
    status: "AVAILABLE",
  },
  {
    id: "q-006",
    question_number: 6,
    category: "AI & Machine Learning",
    difficulty: "Hard",
    base_price: 350,
    reward_points: 800,
    question_text: "What is the key difference between RLHF (Reinforcement Learning from Human Feedback) with PPO versus DPO (Direct Preference Optimization)?",
    answer_clue: "DPO eliminates the explicit reward model and reinforcement learning training loop by directly optimizing policy on paired preferences.",
    status: "AVAILABLE",
  },
  {
    id: "q-007",
    question_number: 7,
    category: "AI & Machine Learning",
    difficulty: "Medium",
    base_price: 180,
    reward_points: 400,
    question_text: "What retrieval technique dynamically supplements an LLM's context window with verified external vector database chunks before inference?",
    answer_clue: "RAG (Retrieval-Augmented Generation)",
    status: "AVAILABLE",
  },
  {
    id: "q-008",
    question_number: 8,
    category: "AI & Machine Learning",
    difficulty: "Easy",
    base_price: 100,
    reward_points: 250,
    question_text: "Which open-source machine learning framework was originally developed by Google Brain and released under Apache 2.0 in 2015?",
    answer_clue: "TensorFlow",
    status: "AVAILABLE",
  },
  {
    id: "q-009",
    question_number: 9,
    category: "AI & Machine Learning",
    difficulty: "Medium",
    base_price: 250,
    reward_points: 550,
    question_text: "What metric is computed as the geometric mean of precision scores for n-grams, typically used to evaluate machine translation output against human reference?",
    answer_clue: "BLEU Score (Bilingual Evaluation Understudy)",
    status: "AVAILABLE",
  },
  {
    id: "q-010",
    question_number: 10,
    category: "AI & Machine Learning",
    difficulty: "Hard",
    base_price: 320,
    reward_points: 750,
    question_text: "In modern LLM inference, what technique caches keys and values to avoid recomputing past tokens during autoregressive token generation?",
    answer_clue: "KV Cache (Key-Value Cache / PagedAttention)",
    status: "AVAILABLE",
  },

  // ==========================================
  // CATEGORY: CLOUD, DEVOPS & INFRASTRUCTURE (11-20)
  // ==========================================
  {
    id: "q-011",
    question_number: 11,
    category: "Cloud & DevOps",
    difficulty: "Easy",
    base_price: 110,
    reward_points: 260,
    question_text: "What declarative language and tool created by HashiCorp is the de-facto standard for Infrastructure as Code (IaC)?",
    answer_clue: "Terraform (using HCL - HashiCorp Configuration Language)",
    status: "AVAILABLE",
  },
  {
    id: "q-012",
    question_number: 12,
    category: "Cloud & DevOps",
    difficulty: "Medium",
    base_price: 200,
    reward_points: 460,
    question_text: "In Kubernetes, what controller ensures that a specified number of pod replicas are running across the cluster nodes at all times?",
    answer_clue: "ReplicaSet (or Deployment Controller)",
    status: "AVAILABLE",
  },
  {
    id: "q-013",
    question_number: 13,
    category: "Cloud & DevOps",
    difficulty: "Hard",
    base_price: 320,
    reward_points: 720,
    question_text: "What Linux kernel feature, combined with namespaces, forms the fundamental isolation backbone behind Docker containers to limit memory and CPU?",
    answer_clue: "cgroups (Control Groups)",
    status: "AVAILABLE",
  },
  {
    id: "q-014",
    question_number: 14,
    category: "Cloud & DevOps",
    difficulty: "Easy",
    base_price: 100,
    reward_points: 240,
    question_text: "What Google Cloud serverless compute product allows developers to run stateless containers invokable via HTTP requests without managing servers?",
    answer_clue: "Google Cloud Run",
    status: "AVAILABLE",
  },
  {
    id: "q-015",
    question_number: 15,
    category: "Cloud & DevOps",
    difficulty: "Medium",
    base_price: 240,
    reward_points: 520,
    question_text: "What deployment strategy routes 5-10% of user traffic to the newly deployed release version before directing 100% of production traffic?",
    answer_clue: "Canary Deployment",
    status: "AVAILABLE",
  },
  {
    id: "q-016",
    question_number: 16,
    category: "Cloud & DevOps",
    difficulty: "Medium",
    base_price: 190,
    reward_points: 420,
    question_text: "Which distributed key-value store does Kubernetes use as its single source of truth for all cluster coordination and configuration state?",
    answer_clue: "etcd",
    status: "AVAILABLE",
  },
  {
    id: "q-017",
    question_number: 17,
    category: "Cloud & DevOps",
    difficulty: "Hard",
    base_price: 340,
    reward_points: 780,
    question_text: "What revolutionary Linux kernel technology allows sandboxed bytecode programs to run safely in the OS kernel at event hooks without modifying kernel source code?",
    answer_clue: "eBPF (Extended Berkeley Packet Filter)",
    status: "AVAILABLE",
  },
  {
    id: "q-018",
    question_number: 18,
    category: "Cloud & DevOps",
    difficulty: "Easy",
    base_price: 120,
    reward_points: 270,
    question_text: "What command in Docker builds a lightweight image from a specified recipe file in the current working directory?",
    answer_clue: "docker build -t <tag> .",
    status: "AVAILABLE",
  },
  {
    id: "q-019",
    question_number: 19,
    category: "Cloud & DevOps",
    difficulty: "Medium",
    base_price: 210,
    reward_points: 470,
    question_text: "What open-source metrics monitoring and alerting toolkit uses a pull-based HTTP model with a custom query language named PromQL?",
    answer_clue: "Prometheus",
    status: "AVAILABLE",
  },
  {
    id: "q-020",
    question_number: 20,
    category: "Cloud & DevOps",
    difficulty: "Hard",
    base_price: 300,
    reward_points: 700,
    question_text: "According to the CAP Theorem for distributed data stores, what three guarantees can never be provided simultaneously in the presence of a network partition?",
    answer_clue: "Consistency, Availability, and Partition Tolerance",
    status: "AVAILABLE",
  },

  // ==========================================
  // CATEGORY: WEB & MODERN FRAMEWORKS (21-30)
  // ==========================================
  {
    id: "q-021",
    question_number: 21,
    category: "Web & Frameworks",
    difficulty: "Easy",
    base_price: 100,
    reward_points: 220,
    question_text: "In React 18, what hook is used to access and subscribe to context without wrapping nested render props?",
    answer_clue: "useContext",
    status: "AVAILABLE",
  },
  {
    id: "q-022",
    question_number: 22,
    category: "Web & Frameworks",
    difficulty: "Medium",
    base_price: 200,
    reward_points: 450,
    question_text: "In Next.js App Router, how do you mark a component to be rendered exclusively on the client side with browser interactivity?",
    answer_clue: "'use client' directive at the top of the file",
    status: "AVAILABLE",
  },
  {
    id: "q-023",
    question_number: 23,
    category: "Web & Frameworks",
    difficulty: "Hard",
    base_price: 310,
    reward_points: 710,
    question_text: "What JavaScript engine optimization technique creates hidden classes to fast-track property lookups on dynamic objects?",
    answer_clue: "V8 Hidden Classes (Shapes / Transitions)",
    status: "AVAILABLE",
  },
  {
    id: "q-024",
    question_number: 24,
    category: "Web & Frameworks",
    difficulty: "Easy",
    base_price: 100,
    reward_points: 230,
    question_text: "Which HTTP status code signifies that a requested resource has been permanently moved to a new URI?",
    answer_clue: "301 Moved Permanently",
    status: "AVAILABLE",
  },
  {
    id: "q-025",
    question_number: 25,
    category: "Web & Frameworks",
    difficulty: "Medium",
    base_price: 190,
    reward_points: 430,
    question_text: "What Web API allows browser applications to run background scripts decoupled from the main page thread to enable offline caching and push notifications?",
    answer_clue: "Service Workers",
    status: "AVAILABLE",
  },
  {
    id: "q-026",
    question_number: 26,
    category: "Web & Frameworks",
    difficulty: "Hard",
    base_price: 330,
    reward_points: 760,
    question_text: "In CSS layout engines, what layout model creates a new formatting context with `contain: layout` or `overflow: hidden`?",
    answer_clue: "Block Formatting Context (BFC)",
    status: "AVAILABLE",
  },
  {
    id: "q-027",
    question_number: 27,
    category: "Web & Frameworks",
    difficulty: "Medium",
    base_price: 220,
    reward_points: 490,
    question_text: "What is the difference between `localStorage` and `sessionStorage` in modern HTML5 browsers?",
    answer_clue: "`localStorage` persists across browser sessions and tabs; `sessionStorage` clears when the browser tab/window is closed.",
    status: "AVAILABLE",
  },
  {
    id: "q-028",
    question_number: 28,
    category: "Web & Frameworks",
    difficulty: "Easy",
    base_price: 120,
    reward_points: 270,
    question_text: "What TypeScript utility type constructs a type with all properties of T set to optional?",
    answer_clue: "Partial<T>",
    status: "AVAILABLE",
  },
  {
    id: "q-029",
    question_number: 29,
    category: "Web & Frameworks",
    difficulty: "Medium",
    base_price: 230,
    reward_points: 510,
    question_text: "What binary instruction format for web browsers allows high-performance languages like Rust and C++ to run in the client at near-native speed?",
    answer_clue: "WebAssembly (WASM)",
    status: "AVAILABLE",
  },
  {
    id: "q-030",
    question_number: 30,
    category: "Web & Frameworks",
    difficulty: "Hard",
    base_price: 300,
    reward_points: 690,
    question_text: "What React architectural pattern reconciles virtual DOM trees asynchronously using fiber nodes, priority lanes, and cooperative multi-tasking?",
    answer_clue: "React Fiber Architecture",
    status: "AVAILABLE",
  },

  // ==========================================
  // CATEGORY: CYBERSECURITY & CRYPTOGRAPHY (31-40)
  // ==========================================
  {
    id: "q-031",
    question_number: 31,
    category: "Cybersecurity",
    difficulty: "Easy",
    base_price: 110,
    reward_points: 250,
    question_text: "What security attack injects malicious executable JavaScript code into web applications viewed by unsuspecting victims?",
    answer_clue: "XSS (Cross-Site Scripting)",
    status: "AVAILABLE",
  },
  {
    id: "q-032",
    question_number: 32,
    category: "Cybersecurity",
    difficulty: "Medium",
    base_price: 210,
    reward_points: 470,
    question_text: "Which cryptographic algorithm relies on the mathematical difficulty of factoring the product of two very large prime numbers?",
    answer_clue: "RSA (Rivest-Shamir-Adleman)",
    status: "AVAILABLE",
  },
  {
    id: "q-033",
    question_number: 33,
    category: "Cybersecurity",
    difficulty: "Hard",
    base_price: 330,
    reward_points: 750,
    question_text: "What post-quantum cryptographic lattice-based algorithm was selected by NIST in 2022 as the primary standard for general encryption?",
    answer_clue: "CRYSTALS-Kyber (ML-KEM)",
    status: "AVAILABLE",
  },
  {
    id: "q-034",
    question_number: 34,
    category: "Cybersecurity",
    difficulty: "Easy",
    base_price: 100,
    reward_points: 230,
    question_text: "What web protocol header prevents clickjacking attacks by dictating whether a browser is allowed to render a page in an <iframe>?",
    answer_clue: "X-Frame-Options (or Content-Security-Policy: frame-ancestors)",
    status: "AVAILABLE",
  },
  {
    id: "q-035",
    question_number: 35,
    category: "Cybersecurity",
    difficulty: "Medium",
    base_price: 240,
    reward_points: 520,
    question_text: "What zero-knowledge cryptographic proof construct allows one party to prove they know a statement is true without revealing any secret information?",
    answer_clue: "zk-SNARKs (or Zero-Knowledge Proofs)",
    status: "AVAILABLE",
  },
  {
    id: "q-036",
    question_number: 36,
    category: "Cybersecurity",
    difficulty: "Hard",
    base_price: 320,
    reward_points: 730,
    question_text: "What type of attack abuses CPU speculative execution to leak secret data across hardware isolation boundaries via side-channel cache timing?",
    answer_clue: "Spectre / Meltdown",
    status: "AVAILABLE",
  },
  {
    id: "q-037",
    question_number: 37,
    category: "Cybersecurity",
    difficulty: "Medium",
    base_price: 220,
    reward_points: 480,
    question_text: "What security property ensures that a session key derived from a set of long-term keys will not be compromised even if one of the long-term keys is compromised in the future?",
    answer_clue: "Perfect Forward Secrecy (PFS)",
    status: "AVAILABLE",
  },
  {
    id: "q-038",
    question_number: 38,
    category: "Cybersecurity",
    difficulty: "Easy",
    base_price: 110,
    reward_points: 260,
    question_text: "In JSON Web Tokens (JWT), what are the three parts separated by periods (dots) called?",
    answer_clue: "Header, Payload, and Signature",
    status: "AVAILABLE",
  },
  {
    id: "q-039",
    question_number: 39,
    category: "Cybersecurity",
    difficulty: "Medium",
    base_price: 200,
    reward_points: 440,
    question_text: "What password-hashing function intentionally incorporates salt and an adjustable computational work factor using the Blowfish cipher?",
    answer_clue: "bcrypt (or Argon2 / scrypt)",
    status: "AVAILABLE",
  },
  {
    id: "q-040",
    question_number: 40,
    category: "Cybersecurity",
    difficulty: "Hard",
    base_price: 340,
    reward_points: 790,
    question_text: "What memory safety vulnerability occurs when an application attempts to access a pointer after it has been deallocated, common in C and C++?",
    answer_clue: "Use-After-Free (UAF)",
    status: "AVAILABLE",
  },

  // ==========================================
  // CATEGORY: DATA STRUCTURES & ALGORITHMS (41-50)
  // ==========================================
  {
    id: "q-041",
    question_number: 41,
    category: "Algorithms & DS",
    difficulty: "Easy",
    base_price: 100,
    reward_points: 230,
    question_text: "What is the worst-case time complexity of quicksort when the pivot is consistently chosen as the maximum or minimum element of an already sorted array?",
    answer_clue: "O(n²)",
    status: "AVAILABLE",
  },
  {
    id: "q-042",
    question_number: 42,
    category: "Algorithms & DS",
    difficulty: "Medium",
    base_price: 200,
    reward_points: 450,
    question_text: "Which self-balancing binary search tree guarantees that the heights of the two child subtrees of any node differ by at most one?",
    answer_clue: "AVL Tree",
    status: "AVAILABLE",
  },
  {
    id: "q-043",
    question_number: 43,
    category: "Algorithms & DS",
    difficulty: "Hard",
    base_price: 320,
    reward_points: 740,
    question_text: "What space-efficient probabilistic data structure is used to test whether an element is a member of a set, allowing false positives but never false negatives?",
    answer_clue: "Bloom Filter",
    status: "AVAILABLE",
  },
  {
    id: "q-044",
    question_number: 44,
    category: "Algorithms & DS",
    difficulty: "Easy",
    base_price: 110,
    reward_points: 250,
    question_text: "Which graph traversal algorithm uses a First-In-First-Out (FIFO) queue data structure to visit vertices level by level?",
    answer_clue: "Breadth-First Search (BFS)",
    status: "AVAILABLE",
  },
  {
    id: "q-045",
    question_number: 45,
    category: "Algorithms & DS",
    difficulty: "Medium",
    base_price: 220,
    reward_points: 490,
    question_text: "What algorithm finds the shortest path between nodes in a graph with non-negative edge weights using a priority queue?",
    answer_clue: "Dijkstra's Algorithm",
    status: "AVAILABLE",
  },
  {
    id: "q-046",
    question_number: 46,
    category: "Algorithms & DS",
    difficulty: "Hard",
    base_price: 350,
    reward_points: 800,
    question_text: "What string-searching algorithm constructs a deterministic finite automaton to search for occurrences of a set of pattern words simultaneously in linear time?",
    answer_clue: "Aho-Corasick Algorithm",
    status: "AVAILABLE",
  },
  {
    id: "q-047",
    question_number: 47,
    category: "Algorithms & DS",
    difficulty: "Medium",
    base_price: 210,
    reward_points: 460,
    question_text: "What dynamic programming technique stores intermediate function call results to avoid redundant subproblem calculations in recursive algorithms?",
    answer_clue: "Memoization",
    status: "AVAILABLE",
  },
  {
    id: "q-048",
    question_number: 48,
    category: "Algorithms & DS",
    difficulty: "Easy",
    base_price: 120,
    reward_points: 270,
    question_text: "What is the average and worst-case time complexity of searching for a key in a balanced hash table?",
    answer_clue: "Average: O(1); Worst-case: O(n)",
    status: "AVAILABLE",
  },
  {
    id: "q-049",
    question_number: 49,
    category: "Algorithms & DS",
    difficulty: "Medium",
    base_price: 230,
    reward_points: 500,
    question_text: "Which greedy algorithm finds a minimum spanning tree by growing the tree one edge at a time from an arbitrary starting vertex?",
    answer_clue: "Prim's Algorithm (or Kruskal's Algorithm)",
    status: "AVAILABLE",
  },
  {
    id: "q-050",
    question_number: 50,
    category: "Algorithms & DS",
    difficulty: "Hard",
    base_price: 310,
    reward_points: 710,
    question_text: "What tree data structure enables fast prefix and range queries on multidimensional spatial coordinates, dividing space with alternating hyperplanes?",
    answer_clue: "k-d Tree (k-dimensional Tree)",
    status: "AVAILABLE",
  },

  // ==========================================
  // CATEGORY: DEVELOPER TRIVIA & ARCHITECTURE (51-60)
  // ==========================================
  {
    id: "q-051",
    question_number: 51,
    category: "Developer Lore & Trivia",
    difficulty: "Easy",
    base_price: 100,
    reward_points: 220,
    question_text: "In what year did Linus Torvalds write and release the initial version of Git after conflicts with BitKeeper?",
    answer_clue: "2005",
    status: "AVAILABLE",
  },
  {
    id: "q-052",
    question_number: 52,
    category: "Developer Lore & Trivia",
    difficulty: "Medium",
    base_price: 200,
    reward_points: 440,
    question_text: "Which computer scientist is credited with inventing the concept of the compiler and coined the popular term 'debugging' after finding a moth in the Mark II computer?",
    answer_clue: "Grace Hopper",
    status: "AVAILABLE",
  },
  {
    id: "q-053",
    question_number: 53,
    category: "Developer Lore & Trivia",
    difficulty: "Hard",
    base_price: 330,
    reward_points: 750,
    question_text: "What is the name of the consensus protocol developed by Diego Ongaro and John Ousterhout designed to be much easier to understand than Paxos?",
    answer_clue: "Raft Consensus Algorithm",
    status: "AVAILABLE",
  },
  {
    id: "q-054",
    question_number: 54,
    category: "Developer Lore & Trivia",
    difficulty: "Easy",
    base_price: 110,
    reward_points: 250,
    question_text: "What Google open-source RPC framework uses Protocol Buffers (protobuf) as both its Interface Definition Language and message format?",
    answer_clue: "gRPC",
    status: "AVAILABLE",
  },
  {
    id: "q-055",
    question_number: 55,
    category: "Developer Lore & Trivia",
    difficulty: "Medium",
    base_price: 210,
    reward_points: 470,
    question_text: "In database systems, what does the 'D' in ACID properties stand for, guaranteeing that committed transactions persist even during power loss?",
    answer_clue: "Durability",
    status: "AVAILABLE",
  },
  {
    id: "q-056",
    question_number: 56,
    category: "Developer Lore & Trivia",
    difficulty: "Hard",
    base_price: 320,
    reward_points: 730,
    question_text: "What distributed log architecture developed at LinkedIn was based on the concept of an append-only commit log with partition offsets?",
    answer_clue: "Apache Kafka",
    status: "AVAILABLE",
  },
  {
    id: "q-057",
    question_number: 57,
    category: "Developer Lore & Trivia",
    difficulty: "Medium",
    base_price: 220,
    reward_points: 480,
    question_text: "What programming language was developed at Google by Robert Griesemer, Rob Pike, and Ken Thompson to address multicore concurrent systems?",
    answer_clue: "Go (Golang)",
    status: "AVAILABLE",
  },
  {
    id: "q-058",
    question_number: 58,
    category: "Developer Lore & Trivia",
    difficulty: "Easy",
    base_price: 100,
    reward_points: 240,
    question_text: "What is the standard HTTP port for HTTPS encrypted traffic?",
    answer_clue: "Port 443",
    status: "AVAILABLE",
  },
  {
    id: "q-059",
    question_number: 59,
    category: "Developer Lore & Trivia",
    difficulty: "Hard",
    base_price: 340,
    reward_points: 780,
    question_text: "In distributed database clocks, what hybrid clock combines physical quartz crystals with Lamport logical clocks to provide strictly monotonically increasing timestamps?",
    answer_clue: "Hybrid Logical Clocks (HLC) or Google TrueTime",
    status: "AVAILABLE",
  },
  {
    id: "q-060",
    question_number: 60,
    category: "Developer Lore & Trivia",
    difficulty: "Hard",
    base_price: 350,
    reward_points: 800,
    question_text: "What famous IEEE standard defines 32-bit single-precision and 64-bit double-precision floating-point arithmetic format used by modern computers?",
    answer_clue: "IEEE 754",
    status: "AVAILABLE",
  },
];
